[workspace]
members  = ["crates/org", "crates/wfe-core", "crates/wfd", "crates/wfe", "crates/server"]
resolver = "2"

[workspace.dependencies]
axum               = "0.7"
tokio              = { version = "1", features = ["full"] }
sqlx               = { version = "0.7", features = ["postgres", "mysql", "runtime-tokio-rustls", "uuid", "chrono", "json"] }
tiberius           = { version = "0.12", default-features = false, features = ["rustls", "chrono"] }
tokio-util         = { version = "0.7", features = ["compat"] }
aes-gcm            = "0.10"
rand               = "0.8"
base64             = "0.22"
serde              = { version = "1", features = ["derive"] }
serde_json         = "1"
thiserror          = "1"
uuid               = { version = "1", features = ["v4", "serde"] }
chrono             = { version = "0.4", features = ["serde"] }
async-trait        = "0.1"
opendal            = { version = "0.50", features = ["services-fs", "services-s3"] }
zen-engine         = "0.55"
zen-expression     = "0.55"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http         = { version = "0.5", features = ["cors"] }
dotenvy            = "0.15"
