[package]
name    = "wf-wfe"
version = "0.1.0"
edition = "2021"

[dependencies]
wfe-core       = { path = "../wfe-core" }
wf-org         = { path = "../org" }
sqlx           = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
thiserror      = { workspace = true }
uuid           = { workspace = true }
chrono         = { workspace = true }
async-trait    = { workspace = true }
tracing        = { workspace = true }
reqwest        = { version = "0.11", features = ["json"] }
tokio          = { workspace = true }
zen-expression = { workspace = true }
tiberius       = { workspace = true }
tokio-util     = { workspace = true }
aes-gcm        = { workspace = true }
rand           = { workspace = true }
base64         = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
