[package]
name    = "wf-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wf-server"
path = "src/main.rs"

[dependencies]
wfe-core           = { path = "../wfe-core" }
wf-org             = { path = "../org" }
wf-wfd             = { path = "../wfd" }
wf-wfe             = { path = "../wfe" }
axum               = { workspace = true }
tokio              = { workspace = true }
sqlx               = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
uuid               = { workspace = true }
chrono             = { workspace = true }
opendal            = { workspace = true }
tower-http         = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy            = { workspace = true }
utoipa             = { workspace = true }
utoipa-axum        = { workspace = true }
utoipa-swagger-ui  = { workspace = true }
jsonwebtoken       = "9"
bcrypt             = "0.15"
